# frozen_string_literal: true

# AdminSuite configuration (host app adapter layer).
#
# This file will eventually be generated by `rails g admin_suite:install` when the
# framework is extracted into a gem/engine. Keeping it in-app first makes the
# extraction a mechanical move.
AdminSuite.configure do |config|
  # TechWright SSO: require developer session for all AdminSuite (engine) access.
  config.authenticate = lambda do |controller|
    authenticated =
      if controller.respond_to?(:developer_authenticated?, true)
        controller.send(:developer_authenticated?)
      else
        false
      end

    next if authenticated

    controller.redirect_to controller.main_app.internal_developer_login_path
  end

  # Actor for auditing/actions/authorization (developer when using AdminSuite).
  config.current_actor = lambda do |controller|
    Current.user.presence ||
      (controller.respond_to?(:current_developer, true) ? controller.send(:current_developer) : nil)
  end

  # Optional authorization hook. Host apps can wire Pundit/CanCan/ActionPolicy here.
  config.authorize = nil

  # Sign-out link in the top bar (TechWright developer logout).
  # Set when the gem supports it (e.g. local gems/admin_suite with logout_path).
  if config.respond_to?(:logout_path=)
    config.logout_path = ->(view) { view.main_app.internal_developer_logout_path }
  end

  # Resource definition file globs (host app can override).
  config.resource_globs = [
    Rails.root.join("app/admin/resources/*.rb").to_s
  ]

  config.theme = {
    primary: :emerald,
    secondary: :cyan
  }

  # Portal dashboard DSL globs.
  #
  # These files define AdminSuite portal dashboards via `AdminSuite.portal`.
  config.portal_globs = [
    Rails.root.join("app/admin/portals/*.rb").to_s
  ]

  config.portals = {
    ops: { label: "Ops Portal", icon: "settings", color: :amber, order: 10 },
    email: { label: "Email Portal", icon: "inbox", color: :emerald, order: 20 },
    ai: { label: "AI Portal", icon: "cpu", color: :cyan, order: 30 },
    assistant: { label: "Assistant Portal", icon: "message-circle", color: :violet, order: 40 },
    payments: { label: "Payments Portal", icon: "credit-card", color: :emerald, order: 50 }
  }

  # Custom renderers can be registered here in the future:
  config.custom_renderers[:billing_debug_snapshot] = ->(record, view_context) { view_context.render_billing_debug_snapshot(record) }
  config.custom_renderers[:llm_provider_request_raw] = ->(record, view_context) { view_context.render_llm_provider_payload(record, kind: :provider_request) }
  config.custom_renderers[:llm_provider_response_raw] = ->(record, view_context) { view_context.render_llm_provider_payload(record, kind: :provider_response) }
  config.custom_renderers[:llm_provider_error_response_raw] = ->(record, view_context) { view_context.render_llm_provider_payload(record, kind: :provider_error_response) }
end
